In [27]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.tree import DecisionTreeRegressor, plot_tree, export_graphviz
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import MinMaxScaler,StandardScaler,Normalizer

import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import adam_v2

import rbf_layer
from rbf_layer import InitCentersRandom, InitCentersKMeans, RBFLayer

In [ ]:
X = np.arange(10, 50, 2).reshape(-1,1)

y = np.arange(1, 5, 0.2).reshape(-1,1)

plt.plot(X,y)
plt.show()
X_test = np.array([30]).reshape(-1,1)
dt_reg = DecisionTreeRegressor(max_depth=6)
dt_reg.fit(X,y)

ypred = dt_reg.predict(X_test)
print(ypred)

from sklearn.preprocessing import MinMaxScaler
X = MinMaxScaler().fit_transform(X)
# X_test = MinMaxScaler().fit_transform(X_test)
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
y = ohe.fit_transform(y).toarray()

# print(X)
# print(y)
model = Sequential()
rbflayer = RBFLayer(10,
                        initializer=InitCentersKMeans(X),
                        betas=1,
                        input_shape=(len(X[0]),))
model.add(rbflayer)
model.add(Dense(20))
# model.add(Dense(1))
# model.add(Activation('sigmoid'))
model.compile(optimizer= tf.keras.optimizers.RMSprop(),
              loss=tf.keras.losses.MeanSquaredError(),
              metrics=['accuracy'])
history1 = model.fit(X, y, epochs=500, batch_size=4)
y_pred = model.predict(X_test)
# print(y_pred)
print(ohe.inverse_transform(y_pred))

In [ ]:
plt.plot(history1.history['accuracy'])
plt.plot(history1.history['loss'])
plt.title('train accuracy and loss')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['accuracy', 'loss'], loc='upper left')
plt.show()

In [53]:
x = np.arange(1,13,1).reshape(2,6)
y = np.arange(8,14,1).reshape(1,6)
print(x)
print(y)
X = MinMaxScaler().fit(x)
Xs = StandardScaler().fit(x)
Xn = Normalizer().fit_transform(x)
print(X)
print(Xs)
print(Xn)
Y = X.transform(y)
Ys = Xs.transform(y)
# Yn = Xn.transform(y)
print(Y)
print(Ys)
# print(Yn)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 8  9 10 11 12 13]]
MinMaxScaler()
StandardScaler()
[[0.10482848 0.20965697 0.31448545 0.41931393 0.52414242 0.6289709 ]
 [0.29606845 0.33836395 0.38065944 0.42295493 0.46525043 0.50754592]]
[[1.16666667 1.16666667 1.16666667 1.16666667 1.16666667 1.16666667]]
[[1.33333333 1.33333333 1.33333333 1.33333333 1.33333333 1.33333333]]
